# Default config for manual area setting

[regions]
valley = "valley"
wuling = "wuling"

[bounding_box_valley]
x_percent = 0.054
y_percent = 0.3
width_percent = 0.88
height_percent = 0.9

[bounding_box_wuling]
x_percent = 0.047
y_percent = 0.6
width_percent = 0.523
height_percent = 0.9

[flags]
aspect_ratio = false