[regions]
valley = "valley"
wuling = "wuling"

[bounding_box_valley]
x_percent = 0.052
y_percent = 0.3
width_percent = 0.88
height_percent = 0.9

[bounding_box_wuling]
x_percent = 0.052
y_percent = 0.6
width_percent = 0.52
height_percent = 0.9